# Only used seetings for Predict -------------------------------------------------------------------------------------------------------

model: yolo26n-seg.pt # (str, optional) path to model file, i.e. yolov8n.pt or yolov8n.yaml
data: yolo_dataset/TestVideo.mp4 # (str, optional) path to data file, i.e. coco8.yaml
frame_count: 12 # (int) process every N'th frame
target_class: ["car", "shadow", "truck", "tire"] # (list[string]) which class to segment

# Predict settings -----------------------------------------------------------------------------------------------------
source: # (str, optional) path/dir/URL/stream for images or videos; e.g. 'ultralytics/assets' or '0' for webcam
vid_stride: 1 # (int) read every Nth frame for video sources
stream_buffer: False # (bool) True buffers all frames; False keeps the most recent frame for low-latency streams
visualize: False # (bool) visualize model features (predict) or TP/FP/FN confusion (val)
augment: False # (bool) apply test-time augmentation during prediction
agnostic_nms: False # (bool) class-agnostic NMS
classes: # (int | list[int], optional) filter by class id(s), e.g. 0 or [0,2,3]
retina_masks: False # (bool) use high-resolution segmentation masks (segment)
embed: # (list[int], optional) return feature embeddings from given layer indices

# Val/Test settings ----------------------------------------------------------------------------------------------------
conf: # (float, optional) confidence threshold; defaults: predict=0.25, val=0.001
iou: 0.7 # (float) IoU threshold used for NMS
max_det: 300 # (int) maximum number of detections per image
half: False # (bool) use half precision (FP16) if supported
end2end: # (bool, optional) whether to use end2end head (yolo26, yolov10) for predict/val/export

# Train settings -------------------------------------------------------------------------------------------------------
imgsz: 640 # (int | list) train/val use int (square); predict/export may use [h,w]
device: # (int | str | list) device: 0 or [0,1,2,3] for cuda, 'cpu'/'mps', or -1/[-1,-1] to auto-select idle gpus
batch: 16 # (int | float) batch size as int (e.g. 16), or float 0.0–1.0 for AutoBatch fraction of GPU memory
project: segmentation-deneme # (str, optional) project name for results root
name: deneme2 # (str, optional) experiment name; results in 'project/name'
verbose: true # (bool) print verbose logs during training/val
compile: false # (bool | str) enable torch.compile() backend='inductor'; true="default", false=off, or "default|reduce-overhead|max-autotune-no-cudagraphs"

# visualize settings ---------------------------------------------------------------------------------------------------
show: true # (bool) show images/videos in a window if supported
save_frames: false # (bool) save individual frames from video predictions
save_txt: false # (bool) save results as .txt files (xywh format)
save_conf: false # (bool) save confidence scores with results
save_crop: false # (bool) save cropped prediction regions to files
show_labels: True # (bool) draw class labels on images, e.g. 'person'
show_conf: True # (bool) draw confidence values on images, e.g. '0.99'
show_boxes: True # (bool) draw bounding boxes on images
line_width:
  # (int, optional) line width of boxes; auto-scales with image size if not set

